name: Build CI

on:
    repository_dispatch:
     # types: [ npm, version ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [13.x]

    steps:
    - name: Event Input
      run: |
        echo action: ${{ github.event.action }}
        echo label: ${{ github.event.client_payload.label }}
    - name: "@thzero/Library Build CI"
      uses: thzero/library_build_action@v0.1-beta
      with:
        type: ${{ github.event.action }}
        label: ${{ github.event.client_payload.label }}
