
name: Build CI

on:
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
        tags:
          description: 'Build'

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - name: Package Output
      run: |
        cat package.json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    # - run: npm install
    # - run: npm run build --if-present
    # - run: npm test
    - run: npm install -g npm-check-updates
    - run: ncu -u
    - name: Commit changes
      if: ${{ success() }}
      run: |
        git config --global user.name '${{ github.repository_owner }}'
        git config --global user.email '${{ github.repository_owner }}@users.noreply.github.com'
        git add .
        git commit -m "npm updates"
        git push
    - name: Create Pull Request
      if: ${{ success() }}
      id: cpr
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     commit-message: npm updates
    #     title: 'npm updates'
    #     #labels: report, automated pr
    #     base: master
    #     # delete-branch: true
    # - name: Check Pull Request Output
    #   run: |
    #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
    #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      uses: repo-sync/pull-request@v2
      with:
        source_branch: dev
        destination_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Request Output
      run: |
        echo ${{ steps.cpr.outputs.pr_url }}
        echo ${{ steps.cpr.outputs.pr_number }}
    - name: Merge pull request
      if: ${{ steps.cpr.outputs.pr_number > 0 && success() }}
      uses: sudo-bot/action-pull-request-merge@v1.1.1
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pr_number }}
